package br.com.oncast.ontrack.client.services.authentication;

import java.util.Date;

import br.com.oncast.ontrack.shared.model.user.User;

import com.google.gwt.user.client.Cookies;
import com.google.gwt.user.datepicker.client.CalendarUtil;

public class UserProviderService {

	private static final String USER_SESSION_ID = "userSessionId";

	public void setAuthenticatedUser(final User authenticatedUser) {
		// TODO ++++Use a encrypted sessionId generated by server.
		final Date expirationDate = new Date();
		CalendarUtil.addDaysToDate(expirationDate, 14);
		Cookies.setCookie(USER_SESSION_ID, authenticatedUser.getEmail(), expirationDate);
	}

	public boolean isCurrentUserAuthenticated() {
		final String sessionId = Cookies.getCookie(USER_SESSION_ID);

		return sessionId != null;
	}

	public void logoutCurrentUser() {
		Cookies.removeCookie(USER_SESSION_ID);
	}

	public String getCurrentUserId() {
		return Cookies.getCookie(USER_SESSION_ID);
	}
}
