package br.com.oncast.ontrack.client.services.authentication;

import br.com.oncast.ontrack.shared.model.user.User;

import com.google.gwt.user.client.Cookies;

public class UserProviderService {

	private static final String USER_SESSION_ID = "userSessionId";

	public void setAuthenticatedUser(final User authenticatedUser) {
		// FIXME Use a encrypted sessionId generated by server.
		// FIXME Use expiration date
		Cookies.setCookie(USER_SESSION_ID, authenticatedUser.getEmail());
	}

	public boolean isCurrentUserAuthenticated() {
		final String sessionId = Cookies.getCookie(USER_SESSION_ID);

		return sessionId != null;
	}

	public void logoutCurrentUser() {
		Cookies.removeCookie(USER_SESSION_ID);
	}

	public String getCurrentUserId() {
		return Cookies.getCookie(USER_SESSION_ID);
	}
}
