package br.com.oncast.ontrack.server.services;

import br.com.oncast.ontrack.server.configuration.Configurations;
import br.com.oncast.ontrack.shared.model.project.ProjectRepresentation;
import br.com.oncast.ontrack.shared.places.PlacesPrefixes;

import com.google.gwt.place.shared.PlaceHistoryMapper;

/**
 * Since GWT URLs are generated by {@link PlaceHistoryMapper}, which is a client class, URLs cannot be generated with the default implementation.
 * Until a custom implementation of the history mapper is made, this class duplicates the default behavior.
 */
public class CustomUrlGenerator {
	public static String forProject(final ProjectRepresentation project) {
		final String string = getAnchorForProject(project);
		return Configurations.getInstance().getApplicationBaseUrl() + string;
	}

	private static String getAnchorForProject(final ProjectRepresentation project) {
		return "#" + PlacesPrefixes.PLANNING + ":" + project.getId();
	}
}
